### ISSUE TITLE
Android - Error importing file when trying to upload image from gallery

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-android#104]
Android wallet app 1.1.6.rc1 - tst
Samsung S20plus
Android 11

When trying to upload image from gallery I always get an error "Error importing file"

![image](https://user-images.githubusercontent.com/81565834/131495847-ce9e2665-6f2b-4894-85e0-fb8f10f6b1be.png)
![image](https://user-images.githubusercontent.com/81565834/131495879-e0474463-c700-469c-95b0-1f8304908c2b.png)
![image](https://user-images.githubusercontent.com/81565834/131495908-e3dd7817-6750-4c4d-9658-97c90645bf35.png)
![image](https://user-images.githubusercontent.com/81565834/131495953-3fe71e05-4847-45ff-8dc6-3dc697cc0062.png)

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/105
