### ISSUE TITLE
Display certificate date instead of scanned date in certificate list

### ISSUE THREAD

**Issue by stefanoschrs** [eu-digital-green-certificates/dgca-wallet-app-android#126]
## Expected Benefits

- Easier to select the certificate you want, in case you have multiple tests
- Not intuitive to remember the day you scanned a certificate but rather the day you did the test/ vaccine

## Current Implementation

![Screenshot_20210923](https://user-images.githubusercontent.com/4215699/134477267-9343c98e-85d6-4732-9991-eb5ca20e3a6b.png)
![Screenshot_20210923](https://user-images.githubusercontent.com/4215699/134477499-1d6c5ccc-f526-4930-9625-f72c3bbfd6db.png)
![Screenshot_20210923](https://user-images.githubusercontent.com/4215699/134477515-67e784bf-0c77-4751-9192-24149c02e658.png)

## Suggested Enhancement

![Screenshot_20210923](https://user-images.githubusercontent.com/4215699/134477305-405854e5-aef1-422d-bc3d-113c2aa0e8dc.png)

**Comment by RalicaY** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/127

**Comment by kerstin-oppermann-tsi** [comment]
retested with wallet 1.2.5.-acc (32)
