### ISSUE TITLE
[Android] For REC Certificates Only the Ones which Are Valid at Least 2 Days After the Day of Travel Are Found During Checkin/Booking

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#135]
## Describe the bug
For REC Certificates Only the Ones which Are Valid at Least 2 Days After the Day of Travel Are Found During Checkin/Booking.  But Certificates which expire one or two days after the day of travel are not offered by the wallet app although the names match.

For Example -- travel date is 08. October 2021 and in the wallet app are REC certificates which expire on:
A) 08. October 2021;
B) 09. October 2021;
C) 10. October 2021;
D) 11. October 2021;
E) 12. October 2021.

All the data (incl. Name ) are identical in all of the certificates, only the expiry dates differ as shown above.  Given a travel date of 08. October 2021, the wallet app matches only certificates D) and E).  See attached Video.

## Expected behaviour
All certificates should be matched because they are all valid with respect to the date of travel.

## Technical details
Wallet App Version 1.2.3-acc (19)
Galaxy XCover 4, Android 9
![Booking_08102021](https://user-images.githubusercontent.com/76050122/136432095-48704dfd-5473-4081-a030-32e97920d2f3.png)

https://user-images.githubusercontent.com/76050122/136432174-ffd27a01-01e6-4b89-942b-c61dd0a0efd3.mp4

**Comment by RalicaY** [comment]
@kerstin-oppermann-tsi could you please retest this when the booking demo works again?

**Comment by oleksandrsarapulovgl** [comment]
@kerstin-oppermann-tsi behavior seems to be correct. The deal is check in QR provides valid from and valid to values. And certificates should be valid during the dates. Check in valid to date - is equal, as I understand, to current day + 2 days.

Here is an example of related JSON:

`{
  "iss": "https://dgca-booking-demo-eu-test.cfapps.eu10.hana.ondemand.com/api/identity",
  "exp": 1634567239,
  "sub": "b95792fb-21b2-4edb-a0bb-960d6a26e402",
  "aud": "https://dgca-validation-service-eu-acc.cfapps.eu10.hana.ondemand.com/validate/b95792fb-21b2-4edb-a0bb-960d6a26e402",
  "t": 2,
  "v": "1.0",
  "iat": 1634563639,
  "vc": {
    "lang": "en-en",
    "fnt": "SARAPULOV",
    "gnt": "ALEX",
    "dob": "1990-01-01",
    "coa": "MF",
    "cod": "RU",
    "roa": "MF",
    "rod": "RU",
    "type": [
      "r",
      "v",
      "t"
    ],
    "category": [
      "Standard"
    ],
    "validationClock": "2021-10-19T21:47:03+00:00",
    "validFrom": "2021-10-19T13:23:03+00:00",
    "validTo": "2021-10-21T13:23:03+00:00"
  },
  "jti": "61c5afd5-4fee-4468-b29f-096b7c6f7e75"
}`

**Comment by oleksandrsarapulovgl** [comment]
@SchulzeStTSI could you please comment here?
