### ISSUE TITLE
[Android-Wallet] Revoked Certificates are Evaluated as Valid

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#164]
## Describe the bug
Revoked certificates get evaluated as valid.

## Expected behaviour

Revoked certificates get evaluated as invalid.

## Steps to reproduce the issue
1. Claim a revoked certificate;
2. Load the certificate;
3.  Click check validity for chosen country and date, while the certificate is revoked;
4.  App says: "Valid certificate".
## Technical details
Galaxy XCover 4, Android 9,
Wallet App Android, Version: 1.2.8-without-tan-request-tst (37)

## Additional context
For about 1 second while loading the revoked certificate, one sees a red text saying "Revoked !" -- yet the text flashes out as soon as the certificate is loaded. (See attached video).

https://user-images.githubusercontent.com/76050122/155003670-834dfdd2-4242-4a44-ae1c-599a908b89c0.mp4

**Comment by RalicaY** [comment]
The current wallet release 1.2.8-tst (40) does not show the red text "Revoked!" on loading the revoked certificates.

**Comment by oleksandrsarapulovgl** [comment]
Checked it, and found an issue with signatures calculation. So, I fixed it, and published new builds:

1.2.8-tst (41)

FYI: @RalicaY

**Comment by kerstin-oppermann-tsi** [comment]
Checked with new version and it works now as aspected.
![image](https://user-images.githubusercontent.com/81565834/155319208-0281d6da-315d-4d50-9258-2ad168ef9aa0.png)
![image](https://user-images.githubusercontent.com/81565834/155319258-fdef5a76-2f3a-435a-b943-969291164d0e.png)
@RalicaY maybe you can check issue by yourself to close the ticket.

**Comment by RalicaY** [comment]
@kerstin-oppermann-tsi @oleksandrsarapulovgl  @ltranvan 
With the current wallet app for android  1.2.8-tst (41) I am not able to see this above certificate as revoked.  As a matter of fact, I cannot see the text "revoked" any more in any certificate whatsoever. See attached video.

https://user-images.githubusercontent.com/76050122/155534857-dffb4ba5-c44f-4c8f-9b18-86231ed64fd3.mp4

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY I claimed the Pavel Chekov certificate twice and both are displayed as revoked in my wallet 1.2.8.-tst(41)
![image](https://user-images.githubusercontent.com/81565834/155536939-a0af0f99-ab70-4e19-846e-3daf2ee325a8.png)
![image](https://user-images.githubusercontent.com/81565834/155537004-6e7bfe61-40df-4541-97b2-7165f100837b.png)

**Comment by kerstin-oppermann-tsi** [comment]
And also another revocation certificate works fine for me.
![image](https://user-images.githubusercontent.com/81565834/155537575-9f4bfbb2-fa82-4941-95b2-eacb2fc0386b.png)
@RalicaY could you reinstall the wallet app? 
@Hendrik-Schmidt-Schierhorn-TSI  can you please recheck.

**Comment by RalicaY** [comment]
@kerstin-oppermann-tsi It is a reinstall already, the problem persists still.

**Comment by michawol** [comment]
![Screenshot from 2022-02-24 15-17-54](https://user-images.githubusercontent.com/97519435/155541944-48f10cfa-0f7c-42f1-aa45-552ecf564b53.png)

**Comment by michawol** [comment]
new TAN now: RW69L2XK

**Comment by kerstin-oppermann-tsi** [comment]
neue TAN: Z7HH8MQP
