### ISSUE TITLE
[Android-Wallet-App] Share PDF to Printer Produces Error or Crash

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#166]
## Describe the bug
Trying out to print a DCC Certificate  via Button "Share PDF" leads to an error "Ladefehler. Dateien in nicht unterstützten Formaten wurden nicht importiert.".  Sporadically this causes the app to crash as well. Video is attached. 

## Technical details
Galaxy XCover 4, Android 9
Wallet App for Android 1.2.8-tst (41)

https://user-images.githubusercontent.com/76050122/155482430-d3e27db2-623c-4e67-992f-0a1e0d1e02e7.mp4

**Comment by RalicaY** [comment]
The same error is produced after trying to print an imported NON-DCC PDF (see attached exmple PDF-file).  The wallet app imports it successfully but the PDF-Share (pdf-export) to printer produces the same erorr: "LADEFEHLER. Dateine in nicht unterstützen Format ..." 
[1645644729156.pdf](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/files/8131001/1645644729156.pdf)

**Comment by RalicaY** [comment]
Issue persists in Version 1.3.0-tst (41), Galaxy XCover 4, Android 9

**Comment by oleksandrsarapulovgl** [comment]
PR with fix: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/189

**Comment by ltranvan** [comment]
tvt, 09.05.22: retest succeeded.
