### ISSUE TITLE
[Android wallet app] - transfer a DCC via NFC is not received by the walletapp

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-android#167]
## Describe the bug
if a DCC is sent from smartphine device A to smartphone device B via NFC, it does not arrive directly in the wallet app on device B. The sent file ends up in the file system of Device B and must first be imported.

## Expected behaviour
a DCC sent via NFC should be received directly in the WalletApp

## Steps to reproduce the issue

1. select at device A a DCC and press "share pdf" or "Share image" button
2. sent the DCC to Device B
3. the DCC is not received by the walletApp

## Technical details
WalletApp 1.2.8-tst (41)
Xiaomi Mi Note 10 Lite

**Comment by RalicaY** [comment]
Issue persists in Android Wallet App 1.3.0 (41)

**Comment by MykhailoNester** [comment]
@RalicaY Fixed in: 1.3.2-(50)

**Comment by ltranvan** [comment]
tvt, 09.05.22: Retest failed. 
After clicking the NFC-ON-button in the the source-device (in the DCC) and the menu-item "Scan NFC code" on the Target-device, the user get a sand-clock in the target device with the message "NFC enabled", but nothing then happens (more than 5 minutes!!!).

**Comment by MykhailoNester** [comment]
@ltranvan could you specify your devices on which you tested?
Also @Hendrik-Schmidt-Schierhorn-TSI could you check this build on your devices maybe it will work for you ?

**Comment by MykhailoNester** [comment]
@ltranvan did a quick test on my devices Pixel 3XL and Sumsung A52 
Verifier: Version 1.3.2-tst-bloom (61)
Wallet: Version 1.3.2-tst (50)

Check this video. Different devices have different nfc chip location. So If I hold this two devices near each other back side to front side of second device it will not work. Only when I hold them back to back.

https://user-images.githubusercontent.com/9447674/167568185-30bffb42-f9e3-499b-9036-f1e73a7e72cc.mp4

**Comment by ltranvan** [comment]
@MykhailoNester: the transfer-test per NFC was carried out between Samsung S10 and S21 FE 5G and both with the WalletApp version 1.3.2(50).
Attention: the QR-certificate should be transfered from Wallet to Wallet as described above in ticket and NOT freom Wallet to Verifier :-) !

**Comment by MykhailoNester** [comment]
:) Yeah my bad I'll check it now, but NFC feature didn't work for all devices wallet/wallet and verifier/wallet and this fix in my PR should fix at least wallet/verifier connection now. 
I'll retest wallet/wallet

**Comment by kerstin-oppermann-tsi** [comment]
@michawol @RalicaY Please recheck with wallet 1.3.2-tst (51)

**Comment by MykhailoNester** [comment]
@ltranvan  Fixed in build: Version 1.3.2-tst (51)
Wallet/wallet dcc transfer works on my side now.

https://user-images.githubusercontent.com/9447674/167606636-76fc213c-87e0-4486-86ca-3e291633ce73.mp4

**Comment by RalicaY** [comment]
Test unsuccessful:  origin device says "New tag detected" with empty screen and source device says "NFC enabled" on empty screen with rotating circle icon. Wallet App 1.3.2 (50)

**Comment by ltranvan** [comment]
tvt, 10.05.22: same test result like from Ralica was observed with my both devices S21 FE and S10. Please check. Thank.

**Comment by MykhailoNester** [comment]
@RalicaY it was fixed in 1.3.2-tst (51) not (50)

**Comment by MykhailoNester** [comment]
@ltranvan you also tested on build 50 ? please check if it was 51 as on my side it works video above ^. Scan both devices back side to back side. Different devices have different chip position.

**Comment by ltranvan** [comment]
No. i have tested it with 1.3.2 (51) on both side. But a new version 1.3.2 (52) is comming today and i will try it again and post its result here :-).

**Comment by MykhailoNester** [comment]
@RalicaY @ltranvan  can you scan Wallet with DCC and enabled NFC feature with `NFC Tools` app from google play market?

Below attached result from old android 4.0 Samsung device which was able to scan this NFC tag from Wallet and you can see Record 1 has text from QR code.  Can you check it was is the result on your side.

![20220511_120251 (1)](https://user-images.githubusercontent.com/9447674/167824745-b0a4f2c2-26a5-4234-8801-5a9fef133a27.jpg)

**Comment by MykhailoNester** [comment]
Latest build 52 contains all changes for NFC. Also works on my side.

**Comment by MykhailoNester** [comment]
Also during test check this configuration of QR code:

<img width="447" alt="Screenshot 2022-05-12 at 17 39 54" src="https://user-images.githubusercontent.com/9447674/168101387-7102103c-263a-43fd-a857-761d21c0a657.png">
<img width="480" alt="Screenshot 2022-05-12 at 17 40 01" src="https://user-images.githubusercontent.com/9447674/168101399-0b81e9f5-4df9-4f7d-bd28-d7f99146463e.png">

**Comment by MykhailoNester** [comment]
@RalicaY @ltranvan 
Fixed payload size limit in build Version 1.3.2-tst (53). Please retest with QR code above.

**Comment by ltranvan** [comment]
tvt, 13.05.22: Retested with Android-version 1.3.2-TST (53).
NFC-Transfer from Samsung S21 FE to Samsung S10 works as expected.
