### ISSUE TITLE
[Android wallet app] - update manually of the revocation state is not possible

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-android#168]
## Describe the bug
if you click the update button for the revocation state, no update is performed, at least the date and time are not updated

## Expected behaviour
the date and time is updating, after you click the update button

## Steps to reproduce the issue

1. open walletApp
2. go to settings
3. click the update button in the row "update revocation state"

## Technical details
WalletApp 1.2.8-tst (41)
Xiaomi Mi Note 10 Lite

**Comment by michawol** [comment]
[Uploading myloggi.txt…]()

**Comment by michawol** [comment]
workaround:
uninstall the app and reinstall it.

**Comment by kerstin-oppermann-tsi** [comment]
For me this issue happened more time in the last days. On Samsung S20 plus.
Workarround fresh installing the app helps. But for that I had to claim all certicates for new.
Maybe if is time and possibility, someone can have a look on this issue what could be the reason for. @oleksandrsarapulovgl @MykhailoNester ?

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY @michawol can you recheck this issue. On my side this happens no more since Oleksandr did a fix in wallet app on related issue.

**Comment by RalicaY** [comment]
For me the issue still exists, WalletApp 1.2.8-tst (41), Galaxy XCover 4, Android 9

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY Did you see a message like "Last update failed"? Or only no update of date/time?

**Comment by RalicaY** [comment]
No, I do not see such a message but only the update of date/time remains without being updated since installation.

**Comment by kerstin-oppermann-tsi** [comment]
Yes think the "fix" is only in version after 3th of march. I had a look into conversion about it.

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY can you please recheck

**Comment by RalicaY** [comment]
I get the same issue with Wallet App Version 1.3.0 (41)

**Comment by kerstin-oppermann-tsi** [comment]
Is fixed - @RalicaY @michawol you can retest in wallet 1.3.0(43)

**Comment by michawol** [comment]
Tested with WalletApp 1.4.0 (45) - manually update is working
