### ISSUE TITLE
[Android-Wallet] Claimed Certificate Does Not Get Deleted via the Three Dots Delete

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#180]
## Describe the bug
Trying to delete a claimed certificate via the three dots->delete does not result in deleting the certificate (see attached video).

## Technical details

Android Wallet App 1.3.0 (41)
Galaxy XCover 4, Android 9

## Additional context
Yet, deletion via the pop-up menu works (when pressing and holding on the certificate in the list view)

https://user-images.githubusercontent.com/76050122/162789622-8412d12a-c47a-4f06-945c-976c9b22ca2b.mp4

**Comment by MykhailoNester** [comment]
Fixed in PR:
https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/184

**Comment by MykhailoNester** [comment]
Build:1.4.0-tst (45)

**Comment by ltranvan** [comment]
tvt, 24.04.2022: Retest successfully carried out.  After clicking on the "Delete-Item" behind the three-dots menu of the credetial, the associated credential is deleted.
