### ISSUE TITLE
[Android-Wallet-App] Revoked Certificates are not Shown as "Revoked"

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#181]
## Describe the bug

Claimed revoked certificates are not shown as "revoked".  There is no indication of revocation to be seen in the wallet app.  
## Expected behaviour
Claimed certifiates that are revoked should be indicated as "revoked".

## Technical details
Wallet App 1.3.0 (41)
Galaxy XCover 4, Android 9

**Comment by kerstin-oppermann-tsi** [comment]
for me it works in 1.4.0(45). @RalicaY  can you recheck please

**Comment by ltranvan** [comment]
tvt, 26.04.22: Positive vom Michael W. am 25.04.2022 retestet. Ticket wird geschlossen.
