### ISSUE TITLE
[Android Wallet App] Trust Issuer is not added in IssuersList despite Consent

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#185]
A Verifiable Credential signed by an issuer who was not on the Gateway was saved in the wallet app after granting consent.  Althoug hthe credential was saved in the wallet app, the issuer itself was apparently not saved in the app's local issuer list because on second scan the app asked for granting consent for the same credential and issuer.

## Expected behaviour
Once we have granted consent for the issuer, if we scna the credential again, the app should recognize it as valid instead of ask for consent a second time.

## Technical details
Wallet App for Android 1.4.0(45)
![private_issuer(1)](https://user-images.githubusercontent.com/76050122/165323749-559670dd-3f95-4750-af6e-0b4f36a31802.png)

**Comment by MykhailoNester** [comment]
Fixed in 1.4.1 (46)(47)

**Comment by ltranvan** [comment]
Already retested with TCs 6713, 6653.
