### ISSUE TITLE
[Android-Wallet-App] Credential is claimend in Wallet, but the content is not diplayed except for raw data

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#186]
## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by ltranvan** [comment]
tvt, 11.05.2022: No Bug because there is no requirement about how the content should be structured and displayed. 
But the raw-datas are displayed on the screen for the user.
