### ISSUE TITLE
Certificate Claiming Problem

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgca-wallet-app-android#22]
There wer problems reported, that the claiming of a certificate has some errors: 

a) If somebody tries to import a certificate and the TAN is not inserted (or canceled), the certificate is imported in the app
b) The new generated TAN is not visible after a valid import
c) Deletion of a certificate ? 

Can you please evaluate this reports to crosscheck if there is any bug or a missing functionality:) Thanks:)

**Comment by oleksandrsarapulovgl** [comment]
Hi Stefan) This has already been fixed, just so far did no release after merge

Closed with PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/20/files

**Comment by oleksandrsarapulovgl** [comment]
Deletion of a certificate - hasn't been implemented. So created a separate ticket for that: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/issues/25
