### ISSUE TITLE
Field "Test Result" in Certificate of type TEST conatins a 9-digit number

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#28]
## Describe the bug

Field "Test Result" in Certificate of type TEST conatins a seemingly random 9-digit number.

## Expected behaviour
The field "Test Result" in Certificate of type TEST should contain the value "DETECTED/UNDETECTED".

## Steps to reproduce the issue
1. Scan a certificate of type TEST

## Technical details
Galaxy XCover 4, Modellnummer: SM-G390F

**Comment by ltranvan** [comment]
tvt, 26.05.2021: Retest with the new Wallet App, Version 1.0.1 successfullly carried out. 
The field "Test Result" in Certificate of type TEST contains now the value "DETECTED" or "UNDETECTED", but no 9 digital number.
Ticket will be closed.
