### ISSUE TITLE
all TANs not found after changing IssuerWebApp URL

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-android#30]
## Describe the bug

After changing the IssuerWebApp to another URL, no TANs are found to claim the qr-code
## Expected behaviour

valid TAN should claim the qr-code
## Steps to reproduce the issue

1. open WalletApp
2. unlock via faceID
3. push the button "Scan code"
4. qr-code will be scaned
5. TAN is requested
6. insert valid TAN
7. see error message: not found

## Technical details

- Host Machine OS (Windows/Linux/Mac):
Samsung Galaxy S9
Android 10

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/31
