### ISSUE TITLE
Please remember increasing versionCode

### ISSUE THREAD

**Issue by IzzySoft** [eu-digital-green-certificates/dgca-wallet-app-android#35]
## Describe the bug

Yesterday you've released v1.0.1 – `versionCode` of the APK is still set to `1` like with v1.0.0, so Android won't recognize it as an update.

## Expected behaviour

`versionCode` was increased since the last release – no matter how much as long as it's "bigger".

## Steps to reproduce the issue

    $ aapt d badging app-release-signed.apk | grep versionCode
    package: name='dgca.wallet.app.android' versionCode='1' versionName='1.0.0' compileSdkVersion='29' compileSdkVersionCodename='10'

You see it even identifies as v1.0.0.

Thanks for fixing :smiley:

**Comment by oleksandrsarapulovgl** [comment]
Sure, I'll be doing this, thank you!

PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/38

**Comment by IzzySoft** [comment]
Thanks! Just in case, please also remember for future releases (for the verification app as well) :wink:

**Comment by oleksandrsarapulovgl** [comment]
Will do my best)
