### ISSUE TITLE
Encrypted storage of DGCs not in line with spec

### ISSUE THREAD

**Issue by fneur** [eu-digital-green-certificates/dgca-wallet-app-android#39]
## Describe the bug

According to the [specification](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v4_en.pdf) (p. 25)

> DGCs will be imported by scanning a base45-encoded QR code and decoding CBOR to JSON.
> Afterwards, it is symmetrically encrypted in the app’s sandbox and the symmetric key is stored in the system’s keychain.

However, the actual cipher used is RSA_ECB_PKCS1_PADDING, hence asymmetric. The relevant call chain is as follows:

`[WalletRepositoryImpl.kt] claimCertificate(...)`
 ---> `[WalletRepositoryImpl.kt] keyStoreCryptor.encrypt(qrCode)`
 ---> `[DefaultKeyStoreCryptor.kt] getSecurityKeyWrapper(keyStore).encrypt(qrCode)`
 ---> `[SecurityKeyWrapper.kt] getCipher(...) = Cipher.getInstance(RSA_ECB_PKCS1_PADDING)`

## Expected behaviour

As stated in the specification, a symmetric encryption algorithm should be used.

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by oleksandrsarapulovgl** [comment]
@SchulzeStTSI Steffen could you please comment if we need to make any changes here?

**Comment by fneur** [comment]
@oleksandrsarapulovgl May I ask another question meanwhile (until Steffen finds the time to answer yours):
Why not use RSA with Optimal Asymmetric Encryption Padding (OAEP)? Is there a specific reason?
(For new applications, one would expect OAEP rather than the old PKCS1 padding)

**Comment by oleksandrsarapulovgl** [comment]
@fneur sure. There is not any specific reason, we can update that

**Comment by fneur** [comment]
@oleksandrsarapulovgl Thanks for your quick reply! But now let's wait and see what Steffen's decision will be. Cheers, F.

**Comment by fneur** [comment]
Steffen must be very busy. So I close this issue now.
