### ISSUE TITLE
DefaultKeyStoreCryptor - key pair not saved in keystore

### ISSUE THREAD

**Issue by fneur** [eu-digital-green-certificates/dgca-wallet-app-android#40]
## Your Question

* Source File: [DefaultKeyStoreCryptor.kt](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/blob/main/app/src/main/java/dgca/wallet/app/android/security/DefaultKeyStoreCryptor.kt)
* Line(s): 62-97 `fun getSecurityKeyWrapper`
* Question:
In `fun getSecurityKeyWrapper` the `keyStore` is first queried for a certain key pair. If it is found, it is wrapped in a
`SecurityKeyWrapper` and returned. Otherwise, a new key pair is generated and also returned. But why is this new key pair
not saved in the `keyStore` (for later retrieval)?

**Comment by oleksandrsarapulovgl** [comment]
@fneur new key pair is saved. It's saved by Keystore itself, when we generate a new key. Here: keyGenerator.generateKey(). For generation - we pass KEY_ALIAS, for further bounding.

I also retested changed once again, and see - that first time key is generated, but with next access - old generated one is being used. Attaching debug screenshots:

![Screenshot from 2021-05-31 09-39-53](https://user-images.githubusercontent.com/82441124/120151218-ab985400-c1f4-11eb-84ae-6836e122c423.png)
![Screenshot from 2021-05-31 09-37-17](https://user-images.githubusercontent.com/82441124/120151224-ac30ea80-c1f4-11eb-823c-acc1699c1f48.png)

**Comment by oleksandrsarapulovgl** [comment]
May I close it @fneur ?

**Comment by fneur** [comment]
Yes, please go ahead. And thanks for the clarification @oleksandrsarapulovgl !
