### ISSUE TITLE
Missing UTC-Hint in "Date of TestResult" and "Date of Date of Collection"

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-android#43]
## Describe the bug
In the WalletApp it is not clear which timezone  is shown

## Expected behaviour
In the Test-QR-code should be clearly shown that it is the UTC-timezone as it is in the ios-version.

## Steps to reproduce the issue
1. create Testcertificate with location time-zone (for example 8:00 AM german time) as seen on screenshot:
![image](https://user-images.githubusercontent.com/81565021/120454129-e389cd80-c393-11eb-8921-3efdb603ed88.png)

2. Open WalletApp
3. Scan the created test-certificate with location time-zone (for example 8:00 AM german time)
4. insert valid tan
5. see test certificate
![image](https://user-images.githubusercontent.com/81565021/120454364-1b911080-c394-11eb-8cf0-212001db9f0d.png)
6. you find a different timezone without a hint

## Technical details
![image](https://user-images.githubusercontent.com/81565021/120454566-49765500-c394-11eb-81c5-cde251322b4d.png)

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix
add the hint (UTC) the Date of collection and Date of Test Result

**Comment by maluueu** [comment]
@rebwalz How did you create the certificate ?

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/47

**Comment by kerstin-oppermann-tsi** [comment]
Fixed in Release 1.0.5
