### ISSUE TITLE
Wrong Label in Country of Vaccination

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-android#44]
## Describe the bug
In the WalletApp it is shown the Label "Country of Vaccination"

## Expected behaviour
In the Test-QR-code should be written"Country of Test".

## Steps to reproduce the issue
1. Open WalletApp
2. Scan a test-certificate
3. insert valid tan
4. see test-certificate
![image](https://user-images.githubusercontent.com/81565021/120455811-5f384a00-c395-11eb-8aed-52c368b03125.png)
5. you see "Country of Vaccination" instead of "Country of Test"

## Technical details
![image](https://user-images.githubusercontent.com/81565021/120454566-49765500-c394-11eb-81c5-cde251322b4d.png)

- Host Machine OS (Windows/Linux/Mac):

## Possible Fix
Change Label to "Country of Test"

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/49
