### ISSUE TITLE
F-Droid release and reproducible builds

### ISSUE THREAD

**Issue by rugk** [eu-digital-green-certificates/dgca-wallet-app-android#50]
## Current Implementation

App is likely only planned to be released in Google Play Store.

## Suggested Enhancement

It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

## Expected Benefits

The benefits are trust (that the code shown here is the code you deliver), security (as untrusted modification of the code is nearly impossible then and you make an independent analysis possible) an increased user base/alternative installation options combined with an increased robustness by not having a single point of failure (Google Play Store) for app delivery.
And also, as said, popularity/marketing if it is visible in the main F-Droid store.

See also https://github.com/corona-warn-app/cwa-app-android/issues/1483 for the same issue for the German Corona-Warn-App that explains more advantages especially of reproducible builds.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
The Swiss app will most likely be published on F-Droid, with reproducible builds (see https://github.com/admin-ch/CovidCertificate-App-Android/issues/40)

I started looking into getting this one there as well but I'm a bit too tired to do things properly I think, will try again tomorrow probably :)

Let me put the link of the MR where I'll be working on it here:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9163

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
It seems this app has a proprietary dependency on com.google.android.gms/play-services-oss-licenses-license

This should be removed before inclusion into F-Droid I would say.

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
See https://github.com/mozilla-mobile/fenix/pull/13767/files for some inspiration :wink:

**Comment by daniel-eder** [comment]
@joerg-oppermann-tsi can you clarify if reproducible builds are in scope for this app, as it's only a template?

**Comment by daniel-eder** [comment]
In F-Droid a fork of https://f-droid.org/de/packages/de.rki.covpass.app/ is available: https://gitlab.com/covpass-android-foss/covpass-android/ 

As there are currently no plans by the European Commission known to me to release on alternative app stores I will close this issue - to be reopened if there is a change.
