### ISSUE TITLE
Fonts for Delete is White with White Background - Not visible

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-wallet-app-android#53]
Scan a QR Code
Enter TAN

Click the Arrow to get into the QR Code
Click on the 3 dots to access the Menu for 
Details and Delete options are White Font on White Background.

Please can this be fixed

Best Regards
Panayiotis Savva

**Comment by kerstin-oppermann-tsi** [comment]
Same issue as https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/issues/57

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/64
