### ISSUE TITLE
White screen is displayed when certificate options menu is opened

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-android#57]
**Environment**
Android Samsung s20+
wallet app-tst-release-signed-1.0.4.apk

**Steps to reproduce:**

1. Create vaccination certificate per issuance web app
2. Claim certificate by wallet app
3. Click on claimed certificate and open it
4. Click on the 3 points for options screen

**Expected result:**
options menu is displayed

**Actual result**
white screen is displayed

![image](https://user-images.githubusercontent.com/81565834/121872338-6e0fec80-cd05-11eb-807e-9941806044f0.png)

PS. functional it works but I cannot see where and for what I have to click

**Comment by kerstin-oppermann-tsi** [comment]
The bug occurs further in Release 1.0.5

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/64

**Comment by kerstin-oppermann-tsi** [comment]
retestet in release 1.0.7
