### ISSUE TITLE
When not set family or given name in issuance web, app shows NULL for the appropriate value

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-android#60]
**Environment**
Issuance Web Portal https://issuance-dgca-test.cfapps.eu10.hana.ondemand.com/
Android Phone
Wallet App 1.0.5.-tst

**Steps to reproduce the issue**

1. Click on Record Vaccination Certification
2. Fill out all mandatory fields 
3. Dont fill out family or given name
4. Scan certificate by Wallet App 

![image](https://user-images.githubusercontent.com/81565834/122246950-449ebe80-cec7-11eb-85c3-fbdffd68276e.png)
![image](https://user-images.githubusercontent.com/81565834/122247004-52544400-cec7-11eb-9094-7230b0104b1d.png)

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/62

![Screenshot_1623923229](https://user-images.githubusercontent.com/82441124/122374328-f4793800-cf6a-11eb-9849-267fd94c0529.png)
![Screenshot_1623923438](https://user-images.githubusercontent.com/82441124/122374331-f511ce80-cf6a-11eb-9772-0debc12ab6ff.png)
![Screenshot_1623923466](https://user-images.githubusercontent.com/82441124/122374334-f5aa6500-cf6a-11eb-9160-7b8849575b4d.png)
![Screenshot_1623923476](https://user-images.githubusercontent.com/82441124/122374336-f642fb80-cf6a-11eb-914e-f65e30360639.png)
