### ISSUE TITLE
Remove field "Date of Test Result" from all App Screens

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-android#61]
The field **Date of test result** is not used anymore since schema 1.3.0 and should be removed from all app screens because it is always empty.

![image](https://user-images.githubusercontent.com/81565834/122250843-4fa71e00-ceca-11eb-8c24-08d02f737097.png)

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/62

![Screenshot_1623923229](https://user-images.githubusercontent.com/82441124/122374328-f4793800-cf6a-11eb-9849-267fd94c0529.png)
![Screenshot_1623923438](https://user-images.githubusercontent.com/82441124/122374331-f511ce80-cf6a-11eb-9772-0debc12ab6ff.png)
![Screenshot_1623923466](https://user-images.githubusercontent.com/82441124/122374334-f5aa6500-cf6a-11eb-9160-7b8849575b4d.png)
![Screenshot_1623923476](https://user-images.githubusercontent.com/82441124/122374336-f642fb80-cf6a-11eb-914e-f65e30360639.png)
