### ISSUE TITLE
How to get the TAN ?

### ISSUE THREAD

**Issue by maluueu** [eu-digital-green-certificates/dgca-wallet-app-android#66]
## Your Question

* Source File: .
* Line(s): .
* Question: I want to import my German certificate into the Wallet App but I'm asked to input a TAN. Where can I get it from?

**Comment by daniel-eder** [comment]
@maluueu Germany has not implemented this functionality. Please use [CovPass](https://digitaler-impfnachweis-app.de/), it can scan certificate QR codes to import them.

**Comment by maluueu** [comment]
@daniel-eder thank you for quick answer. I was just curious if one could also import the German certificate into this app.

BTW: Why are German DGCs shown as invalid in the Verifier App?

**Comment by daniel-eder** [comment]
@maluueu There may be a range of possible issues, but I suspect the issue could be missing public keys. There's already a few related issues open - the member states are working together with us to ensure these issues are sorted out, so it should only be a matter of days. 

If issues persist, feel free to open an issue so this can be looked into more closely!
