### ISSUE TITLE
Auto update QR code

### ISSUE THREAD

**Issue by Ca5dob** [eu-digital-green-certificates/dgca-wallet-app-android#67]
## Auto update QR code

* Source File:
* Line(s):
* Question:for French tousanticovid Android app, English language, Wallet,  should existing QR codes for vaccination be updated automatically to the eu digital QR codes? This is not happening for my group.
*

**Comment by daniel-eder** [comment]
The French app is not part of this GitHub organization, however the code base here does not support any conversion / update of pre-existing qr codes, so I consider it unlikely the French app has this feature.
