### ISSUE TITLE
No value passed for parameter 'x509'

### ISSUE THREAD

**Issue by m2049r** [eu-digital-green-certificates/dgca-wallet-app-android#69]
Build fails with

`e: /src/dgca-wallet-app-android/app/src/main/java/dgca/wallet/app/android/di/DecoderModule.kt: (90, 75): No value passed for parameter 'x509'`

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/72
