### ISSUE TITLE
TAN Code

### ISSUE THREAD

**Issue by SodaFormulas** [eu-digital-green-certificates/dgca-wallet-app-android#73]
Hi,

I just scanned my certificate and the app is asking a TAN Code. I have no idea what it is or what does TAN stand for. It's been supposedly sent to me via e-mail or else, but how (I mean, who has my contact info) and by who is this code supposed to be sent?

I scanned the QR Code (the EU one, not the French 2D-DOC) provided on paper in France by our health insurance system.

Thanks for any info on the matter.

Wallet App version 1.0.7-acc and 1.0.7-tst
OS: Android 11

**Comment by daniel-eder** [comment]
The app builds found on this github organization are not for production use, the apps here are only reference implementations that can be configured by EU member states to work with their national backends, or copied into their existing COVID apps. 
Please use the French national app to be able to use real life certificates.
