### ISSUE TITLE
The details of a scanned QR code are revealed even if a wrong TAN code is provided

### ISSUE THREAD

**Issue by skounis** [eu-digital-green-certificates/dgca-wallet-app-android#75]
## Describe the bug

The 1.0.8-RC-1 build for acc was used for scanning QR codes from the `dcc-quality-assurance` repository. For example:

* https://github.com/eu-digital-green-certificates/dcc-quality-assurance/tree/main/LV/1.3.0

After the scan a screen requests a TAN code. No matter what it is entered in this field the user gets navigated in the next screen where all the details of the QRCode are displayed.

## Expected behaviour

Since we are not in the position to provide the TAN code related to the QR code in question we should not have access to its details. 

## Steps to reproduce the issue
1. Download the latest build of the app for acceptance https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/releases/tag/1.0.8-RC-1
2. Install the app and scan a QR code from:
    - https://github.com/eu-digital-green-certificates/dcc-quality-assurance/tree/main/LV/1.3.0   
3. Enter a random TAN code and select next
4. The details of the QR code are displayed

## Technical details

- Android. Pixel 2

## Possible Fix
Should we prevent this? 

## Additional context
N/A

**Comment by kerstin-oppermann-tsi** [comment]
This issue is obsolete because the behaviour of the wallet app isn't the same like in the 1.0.8 release.
The details are displayed before entering the TAN and after entering a wrong TAN the certificate isn't claimed and you got an error message.
