### ISSUE TITLE
[Android] Humanly Unreadable Fields "Disease or agent targeted", "Type of test" 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#78]
## Describe the bug
The fields "Disease or agent targeted", "Type of test"  should be made humanly readable. Now the values are shown as digits.

## Technical details

Android Wallet App 1.0.8-tst
![Wallet_App_Felde_humanly_unreadable](https://user-images.githubusercontent.com/76050122/125617958-6ff000d7-1ed8-49ce-8698-b824af0bd79f.png)
Galaxy XCover 4, Android 9

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/86

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY could you please check screenshot in the PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/86. Is this what is expected?

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl, yes those values are correct.

**Comment by RalicaY** [comment]
Successfully retested Android Wallet App 1.1.2
