### ISSUE TITLE
Android - Scanning a Test Certificate - the Wallet App does NOT validate (status is "OPEN") selected valid Value „ Rapid immunoassay “ for “Type of Test” and “Roche (SD BIOSENSOR), SARS-CoV-2 Rapid Antigen Test” for „ RAT Test name and manufacturer" 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#79]
## Describe the bug

A valid test certificate is created with the selected valid values “**Rapid immunoassay**” for “**Type of Test**” and “**Roche (SD BIOSENSOR), SARS-CoV-2 Rapid Antigen Test**” for “**RAT Test name and manufacturer**”. Certificate is claimed and saved in the Android WalletApp. The test result is **not detected**.
-	This certificate will be then checked on its validity for DE within the WalletApp. 
-	It is now expected that the WalletApp would show green as a final result and all of the BR for DE are passed. 
But instead of this, 
o	it shows the messegae “Certificate has limitation” and
o	The check for the BR  “Der Antigen-Test muss in der Liste ‘Common list of rapid antigen tests’ der EU enthalten sein” is left **open** and 
o	“LP217198-3” is showed as the value for “Type of Test” and 
o	“1333” is showed as the value for ““RAT Test name and manufacturer”.

## Technical details

Android Wallet App 1.1.0-tst
## Additional context

The same behaviour was observed with Android Verifier App 1.1.6-RC1
![open](https://user-images.githubusercontent.com/76050122/125663371-39cf231e-21c6-4901-9eba-44d74f5c132e.png)

**Comment by ltranvan** [comment]
tvt, 20.07.2021: Retest was carried out at 20.07.2021 with Android-Wallet App V1.1.1-test on test environtment. The described bahaviour didn't occurre anymore. Issue will be closed.
