### ISSUE TITLE
[Android] -- Country cannot be selected

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-android#81]
## Describe the bug

There is no option to select the country when scanning a certificate.  Once claimed, the validity can be checked only for Belgium as it is fixed as the destination country.

## Technical details
Wallet App 1.1.0-tst
Galaxy XCover 4, Android 9

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY can you share a video for this issue?

In my app I can select the country for validation. 
![image](https://user-images.githubusercontent.com/81565834/125832880-21b7d6a3-ccfd-4565-bcfc-76dbe26a6ef9.png)

**Comment by RalicaY** [comment]
https://user-images.githubusercontent.com/76050122/125833213-2a0702d2-13e6-47a3-a4c5-822cd7124757.mp4

**Comment by RalicaY** [comment]
When I tapped on "Belgium" it worked.
