### ISSUE TITLE
Android - TAN input should be after displaying the values of the certificate 

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-android#88]
**## Describe the bug**

When I scan a QR Code at next step should be displayed the details informations of the certificate. 
Steps should be like in iOS wallet app. the behaviour on iOS is according to spec, on Android it is not. 

In iOS steps are like this:
1. scan QR Code
2. display cert details and SAVE button
3. tap on SAVE
4. input TAN

**Comment by kerstin-oppermann-tsi** [comment]
@oleksandrsarapulovgl I moved this issue from iOS to Android because the iOS behaviour is like spec, so Android should be changed according to this.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/90

**Comment by RalicaY** [comment]
@oleksandrsarapulovgl , @Hendrik-Schmidt-Schierhorn-TSI Retest on Android Wallet 1.1.2 was NOT successful -- the old state is to be observed (that is, TAN input is needed before Data can be displayed).

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY looks like that it wasn't merge in current pre-release, sorry. Let's check then in next one please, I'll discuss to prepare one today.

**Comment by oleksandrsarapulovgl** [comment]
@RalicaY could you please recheck on latest build?

**Comment by RalicaY** [comment]
Successfully retested in 1.1.4-tst.
